# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylen_clen_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CutLengthWorkSheet(object):
    def setupUi(self, CutLengthWorkSheet):
        CutLengthWorkSheet.setObjectName("CutLengthWorkSheet")
        CutLengthWorkSheet.resize(577, 554)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CutLengthWorkSheet)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(CutLengthWorkSheet)
        self.graphicsView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.scrollArea = QtWidgets.QScrollArea(CutLengthWorkSheet)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 557, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.pushButton_AddSegment = QtWidgets.QPushButton(CutLengthWorkSheet)
        self.pushButton_AddSegment.setObjectName("pushButton_AddSegment")
        self.verticalLayout_2.addWidget(self.pushButton_AddSegment)

        self.retranslateUi(CutLengthWorkSheet)
        QtCore.QMetaObject.connectSlotsByName(CutLengthWorkSheet)

    def retranslateUi(self, CutLengthWorkSheet):
        _translate = QtCore.QCoreApplication.translate
        CutLengthWorkSheet.setWindowTitle(_translate("CutLengthWorkSheet", "Filament Cut Length WorkSheet"))
        self.pushButton_AddSegment.setText(_translate("CutLengthWorkSheet", "Add Segment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CutLengthWorkSheet = QtWidgets.QWidget()
    ui = Ui_CutLengthWorkSheet()
    ui.setupUi(CutLengthWorkSheet)
    CutLengthWorkSheet.show()
    sys.exit(app.exec_())
