# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylen_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Generate.setObjectName("pushButton_Generate")
        self.gridLayout.addWidget(self.pushButton_Generate, 10, 0, 1, 4)
        self.label_ReportFilePath = QtWidgets.QLabel(self.centralwidget)
        self.label_ReportFilePath.setEnabled(True)
        self.label_ReportFilePath.setObjectName("label_ReportFilePath")
        self.gridLayout.addWidget(self.label_ReportFilePath, 2, 0, 1, 1)
        self.lineEdit_GCodePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_GCodePath.setObjectName("lineEdit_GCodePath")
        self.gridLayout.addWidget(self.lineEdit_GCodePath, 1, 1, 1, 1)
        self.label_GCodeFilePath = QtWidgets.QLabel(self.centralwidget)
        self.label_GCodeFilePath.setEnabled(True)
        self.label_GCodeFilePath.setObjectName("label_GCodeFilePath")
        self.gridLayout.addWidget(self.label_GCodeFilePath, 1, 0, 1, 1)
        self.lineEdit_ReportPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ReportPath.setObjectName("lineEdit_ReportPath")
        self.gridLayout.addWidget(self.lineEdit_ReportPath, 2, 1, 1, 1)
        self.pushButton_OpenReport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenReport.setObjectName("pushButton_OpenReport")
        self.gridLayout.addWidget(self.pushButton_OpenReport, 2, 2, 1, 1)
        self.label_OutputWindow = QtWidgets.QLabel(self.centralwidget)
        self.label_OutputWindow.setObjectName("label_OutputWindow")
        self.gridLayout.addWidget(self.label_OutputWindow, 12, 0, 1, 1)
        self.textBrowser_OutputWindow = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_OutputWindow.setObjectName("textBrowser_OutputWindow")
        self.gridLayout.addWidget(self.textBrowser_OutputWindow, 14, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 11, 1, 1, 1)
        self.label_Progress = QtWidgets.QLabel(self.centralwidget)
        self.label_Progress.setObjectName("label_Progress")
        self.gridLayout.addWidget(self.label_Progress, 11, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_ReportFilePath.setBuddy(self.lineEdit_ReportPath)
        self.label_GCodeFilePath.setBuddy(self.lineEdit_GCodePath)
        self.label_OutputWindow.setBuddy(self.textBrowser_OutputWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_Generate, self.textBrowser_OutputWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pylen Filament Usage Generator"))
        self.pushButton_Generate.setToolTip(_translate("MainWindow", "Click to generate Filament Usage Report"))
        self.pushButton_Generate.setText(_translate("MainWindow", "Generate"))
        self.label_ReportFilePath.setText(_translate("MainWindow", "Report File:"))
        self.lineEdit_GCodePath.setToolTip(_translate("MainWindow", "Path to Gcode File use File->Open "))
        self.label_GCodeFilePath.setText(_translate("MainWindow", "GCodeFile:"))
        self.lineEdit_ReportPath.setToolTip(_translate("MainWindow", "Use FileOpen or Manually set"))
        self.pushButton_OpenReport.setText(_translate("MainWindow", "OpenReport"))
        self.label_OutputWindow.setText(_translate("MainWindow", "Output Window"))
        self.textBrowser_OutputWindow.setToolTip(_translate("MainWindow", "Filament Usage Report window"))
        self.label_Progress.setText(_translate("MainWindow", "Progress"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
